server:
  port: 8084

spring:
  application:
    name: PHARMACY-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/hospital_pharmacy_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    config:
      enabled: false

    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      BILLING-SERVICE:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3

      NOTIFICATION-SERVICE:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
