server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #Mail Trap Service
#  mail:
#    host: sandbox.smtp.mailtrap.io
#    port: 443
#    username: 3b2a705f2880f1
#    password: 398ab90b553c24
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 10000
#          timeout: 10000
#          writetimeout: 10000

  # Config server
  config:
    import: optional:configserver:http://localhost:8888

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970cygsgcicgueknkehcigeigsikcgukgcaugkceskygcgcskchaku
  expiration-ms: 86400000
  refresh-expiration-ms: 604800000

#Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never


# Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

